sudo: false

language: ruby

rvm:
  - 2.3.3
  - 2.4.0

cache: bundler
script: bundle exec middleman build

# safelist
branches:
  only:
  - master
  
before_install:
  - bash -c "gem update --system"

deploy:
  provider: script
  script: bash deploy.sh
    - ruby -e "require 'bundler/middleman'"
  on:
    branch: master
