sudo: false

language: ruby

rvm:
  - 2.3.3
  - 2.4.0

cache: bundler
script: deploy.sh
  
before_install:
  - bash -c "gem update --system"
  
jobs:
  include:
    - stage: deploy
      script: deploy.sh
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: build
        github_token: $GITHUB_TOKEN
       on:
          branch: master


