sudo: false

language: ruby

rvm:
  - 2.3.3
  - 2.4.0

cache: bundler
script:
  - bash deploy.sh

# safelist
branches:
  only:
  - master
  
before_install:
  - bash -c "gem update --system"

deploy:
  provider: pages
  skip_cleanup: true
  local_dir : build
  target_branch : gh-pages
 on:
    branch: master
