sudo: false

language: ruby

rvm:
  - 2.3.3
#  - 2.4.0

cache: bundler
script: bundle exec middleman build

# safelist
branches:
  only:
  - master
  
before_install:
  - bash -c "gem update --system"

#deploy:
#  provider: script
#  script: bash deploy.sh
#    - ruby -e "require 'bundler/middleman'"
#  on:
#    branch: master

deploy:
  provider: pages
  skip_cleanup: true
  local_dir : build
  target_branch : gh-pages
# github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
 on:
    branch: master
