sudo: false

language: ruby

rvm:
  - 2.3.3
  - 2.4.0

cache: bundler
# script: bundle exec middleman build
  
# cache: bundler
# script: deploy.sh

script:
  - bash deploy.sh
  
before_install:
  - bash -c "gem update --system"

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  github_token: $GITHUB_TOKEN
  target_branch: gh-pages
 on:
    branch: master
